parameters:
#    pl_sharer_search.example.class: PlSharer\SearchBundle\Example

services:
#    pl_sharer_search.example:
#        class: %pl_sharer_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
