parameters:
#    pl_sharer_music.example.class: PlSharer\MusicBundle\Example

services:
#    pl_sharer_music.example:
#        class: %pl_sharer_music.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
