<?php

namespace PlSharer\AuthBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MyUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
}
