parameters:
#    pl_sharer_ranking.example.class: PlSharer\RankingBundle\Example

services:
#    pl_sharer_ranking.example:
#        class: %pl_sharer_ranking.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
